### ISSUE TITLE
The standard `ModelOutput` field for any `Score` should be `score`, not `classification`

### ISSUE THREAD

**Issue by endymion** [AnthusAI/Plexus#4]
Continuing along the lines of making "classification" more general (inclusive of scalar predictions and generated content and whatever else) by moving from `Classification` models as base classes to `Score`, we should also change the standard `ModelOutput` [base class field](https://github.com/AnthusAI/Plexus/blob/9c36d920da576a4fcad7e088e02b3d7763879e26/plexus/scores/Score.py#L103) from `classification` to `score`.

**Comment by dereknorrbom** [comment]
https://github.com/AnthusAI/Plexus/commit/cd90c87ab73ddbcc89e0d0b7ce8716f1014b86a4
