### ISSUE TITLE
Does `train_model()` make sense for `AgenticValidator`?

### ISSUE THREAD

**Issue by endymion** [AnthusAI/Plexus#6]
There is a [`train_model()`](https://github.com/AnthusAI/Plexus/blob/9c36d920da576a4fcad7e088e02b3d7763879e26/plexus/scores/AgenticValidator.py#L127-L157) function in the `AgenticValidator` class, but does that make sense?

This needs better documentation, but `train_model()` is a standard lifecycle function for a Plexus `Score` that's vital for ML models that require training weights or whatever and then saving a model artifact file for use during inference.  But the `AgenticValidator` operates on retrained models through APIs, and doesn't require doing anything like that at training time, as far as I know?

Is that functionality in the function right now important for something?  I'm worried that it will never be invoked.

We probably need a standard `document_score()` lifecycle function for Plexus `Score`s that will generate model diagrams for ML models graph diagrams for LangGraph agentic `Score`s, etc.

**Comment by dereknorrbom** [comment]
The base class required it.  I brought up this not making sense for this previously but didn't get an actionable response.

https://github.com/AnthusAI/Plexus/commit/092e04415b8dcb299472345f4697e73744713f06

I implemented a `pass` on `train_model` and gave the method a more appropriate name.

**Comment by endymion** [comment]
Ah, okay, that makes sense.  I was just worried about errors from that function getting called when we call `plexus train ...` on a scorecard with a mixture of those scores and ML scores.
